POST http://localhost:3001/api/singin
Content-Type: application/json

{
  "username": "coder123",
  "email": "test@test.com",
  "password": "supersecretpassword"
}

###

POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "coder123",
  "password": "supersecretpassword"
}

###