# Generated by Django 5.2.5 on 2025-09-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_avatar_userprofile_github_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
